import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { ContactShadows, Environment, OrbitControls } from '@react-three/drei'
import { Suspense, useRef } from 'react'
import { Group, Vector3 } from 'three'
import { VehicleAsset } from './VehicleAsset'
import { RoadSurface } from './RoadSystem'

export type BusinessMode='comfort'|'space'|'safety'|'technology'
const cameraByMode:Record<BusinessMode,Vector3>={comfort:new Vector3(6,2.4,7),space:new Vector3(8,4.8,9),safety:new Vector3(7,7,11),technology:new Vector3(9,10,12)}
function Director({mode}:{mode:BusinessMode}){const {camera}=useThree();useFrame((_,d)=>{camera.position.lerp(cameraByMode[mode],Math.min(1,d*2.3));camera.lookAt(0,mode==='technology'?1:0,0)});return null}
function Capacity(){return <group>{[-2.5,0,2.5].map((x,i)=><group key={x} position={[x,1.1,-.3]}><mesh><capsuleGeometry args={[.34,.8,8,16]}/><meshPhysicalMaterial color={i===1?'#d7bd82':'#66716e'} metalness={.25} roughness={.35} transmission={.12}/></mesh></group>)}<VehicleAsset vehicleId="seven" rotation-y={-.35}/></group>}
function Safety(){return <group><RoadSurface length={30}/><VehicleAsset vehicleId="premium" rotation-y={-.2}/>{[2.1,3.2,4.3].map((r,i)=><mesh key={r} rotation-x={-Math.PI/2} position-y={.06}><ringGeometry args={[r,r+.035,72]}/><meshBasicMaterial color={i===0?'#d8be84':'#48e0bb'} transparent opacity={.6-i*.13}/></mesh>)}</group>}
function Network(){return <group>{[[-5,-3],[-2,2],[1,-2],[4,3],[5,-1],[-4,3]].map(([x,z],i)=><group key={i} position={[x,0,z]}><mesh position-y={.25}><cylinderGeometry args={[.16,.28,.5,12]}/><meshStandardMaterial color="#48e0bb" emissive="#147f69" emissiveIntensity={2}/></mesh><mesh position-y={1.3}><cylinderGeometry args={[.018,.018,2.1,6]}/><meshBasicMaterial color="#48e0bb" transparent opacity={.45}/></mesh></group>)}<VehicleAsset vehicleId="business" scale={.62}/></group>}
function World({mode}:{mode:BusinessMode}){const ref=useRef<Group>(null);useFrame((_,d)=>{if(ref.current)ref.current.rotation.y+=d*(mode==='comfort'?.12:.035)});return <><Director mode={mode}/><group ref={ref}>{mode==='comfort'&&<><mesh rotation-x={-Math.PI/2} position-y={-.04}><circleGeometry args={[6,96]}/><meshPhysicalMaterial color="#161b1a" metalness={.8} roughness={.14} clearcoat={1}/></mesh><VehicleAsset vehicleId="business" rotation-y={-.45}/></>}{mode==='space'&&<Capacity/>}{mode==='safety'&&<Safety/>}{mode==='technology'&&<Network/>}</group><ContactShadows opacity={.75} scale={15} blur={2}/></>}
export function Business3DScene({mode}:{mode:BusinessMode}){return <Canvas shadows dpr={[.75,1.5]} camera={{position:[6,3,8],fov:39}} gl={{antialias:true,powerPreference:'high-performance'}}><color attach="background" args={['#0a0c0d']}/><fog attach="fog" args={['#0a0c0d',16,35]}/><ambientLight intensity={.45}/><spotLight castShadow position={[7,11,6]} intensity={85} angle={.42} penumbra={.8} color={mode==='safety'?'#7ee8d0':'#fff1d4'}/><pointLight position={[-6,3,-3]} intensity={18} color="#48e0bb"/><Suspense fallback={null}><Environment files="/hdr/sky_1k.hdr" environmentIntensity={.7}/><World mode={mode}/></Suspense>{mode==='comfort'&&<OrbitControls enablePan={false} minDistance={5} maxDistance={11} target={[0,.5,0]}/>}</Canvas>}
