import { ContactShadows } from '@react-three/drei'
import { AirportTerminal, CityArchitecture, HotelCurb } from './Architecture'
import { VehicleTransition } from './VehicleTransition'
import type { Place, ServiceId, VehicleId } from '../lib/data'
export function AirportScene({departure=false,vehicle}:{departure?:boolean;vehicle:VehicleId}){return <><AirportTerminal departures={departure}/><VehicleTransition vehicle={vehicle} position={[1,0,2]} rotationY={-.45}/><PickupMarker label={departure?'DEPARTURES':'ARRIVALS'} position={[-3,0,1]}/></>}
export function UrbanPickupScene({place,vehicle}:{place:Place;vehicle:VehicleId}){return <><CityArchitecture city={place.city}/><VehicleTransition vehicle={vehicle} position={[1,0,2]} rotationY={-.45}/><PickupMarker label={place.city.toUpperCase()} position={[-3,0,1]}/></>}
export function RentalShowroomScene({vehicle}:{vehicle:VehicleId}){return <group><mesh position={[0,3,-7]}><boxGeometry args={[22,6,.3]}/><meshStandardMaterial color="#1a1c19" metalness={.55}/></mesh><mesh rotation-x={-Math.PI/2} position-y={-.05}><circleGeometry args={[6,96]}/><meshStandardMaterial color="#22231f" roughness={.2} metalness={.7}/></mesh><mesh rotation-x={-Math.PI/2}><ringGeometry args={[4.2,4.25,96]}/><meshBasicMaterial color="#b89a62"/></mesh><VehicleTransition vehicle={vehicle} rotationY={-.55}/><ContactShadows opacity={.7} scale={12} blur={2}/></group>}
export function ChauffeurScene({vehicle}:{vehicle:VehicleId}){return <><HotelCurb/><VehicleTransition vehicle={vehicle} position={[.5,0,2]} rotationY={-.4}/><PickupMarker label="EXECUTIVE PICKUP" position={[-3,0,1]}/></>}
export function PickupMarker({label: _label,...props}:{label:string;position:[number,number,number]}){return <group {...props}><mesh position-y={.08} rotation-x={-Math.PI/2}><ringGeometry args={[.48,.6,40]}/><meshBasicMaterial color="#d4bb84"/></mesh><mesh position-y={1}><cylinderGeometry args={[.04,.04,2]}/><meshStandardMaterial color="#d4bb84"/></mesh><mesh position-y={2}><octahedronGeometry args={[.22]}/><meshStandardMaterial color="#e0c991" metalness={.5}/></mesh></group>}
export function ServiceSceneManager({service,pickup,vehicle}:{service:ServiceId;pickup:Place;vehicle:VehicleId}){if(service==='self-drive')return <RentalShowroomScene vehicle={vehicle}/>;if(service==='chauffeur')return <ChauffeurScene vehicle={vehicle}/>;if(service==='airport-to-location')return <AirportScene vehicle={vehicle}/>;if(service==='location-to-airport')return <AirportScene departure vehicle={vehicle}/>;return <UrbanPickupScene place={pickup} vehicle={vehicle}/>}
