import { ContactShadows } from '@react-three/drei'
import { AirportTerminal, CityArchitecture, HotelCurb } from './Architecture'
import { RoadSurface } from './RoadSystem'
import { VehicleAsset } from './VehicleAsset'
import type { Place, ServiceId, VehicleId } from '../lib/data'

export function AirportScene({departure=false,vehicle}:{departure?:boolean;vehicle:VehicleId}){return <><RoadSurface/><AirportTerminal departures={departure}/><VehicleAsset vehicleId={vehicle} position={[1,0,2]} rotation-y={-.45}/><PickupMarker position={[-3,0,1]}/></>}
export function UrbanPickupScene({place,vehicle}:{place:Place;vehicle:VehicleId}){return <><RoadSurface/><CityArchitecture city={place.city}/><VehicleAsset vehicleId={vehicle} position={[1,0,2]} rotation-y={-.45}/><PickupMarker position={[-3,0,1]}/></>}
export function RentalShowroomScene({vehicle}:{vehicle:VehicleId}){return <group><mesh position={[0,3,-7]}><boxGeometry args={[22,6,.3]}/><meshStandardMaterial color="#101413" metalness={.7} roughness={.22}/></mesh><mesh rotation-x={-Math.PI/2} position-y={-.05}><circleGeometry args={[6,96]}/><meshPhysicalMaterial color="#181d1c" roughness={.12} metalness={.85} clearcoat={1}/></mesh><mesh rotation-x={-Math.PI/2}><ringGeometry args={[4.2,4.25,96]}/><meshBasicMaterial color="#c6a96f"/></mesh><VehicleAsset vehicleId={vehicle} rotation-y={-.55}/><ContactShadows opacity={.8} scale={12} blur={1.8}/></group>}
export function ChauffeurScene({vehicle}:{vehicle:VehicleId}){return <><RoadSurface/><HotelCurb/><VehicleAsset vehicleId={vehicle} position={[.5,0,2]} rotation-y={-.4}/><PickupMarker position={[-3,0,1]}/></>}
export function PickupMarker(props:{position:[number,number,number]}){return <group {...props}><mesh position-y={.08} rotation-x={-Math.PI/2}><ringGeometry args={[.48,.6,40]}/><meshBasicMaterial color="#48e0bb"/></mesh><mesh position-y={1}><cylinderGeometry args={[.04,.04,2]}/><meshStandardMaterial color="#48e0bb" emissive="#147f69" emissiveIntensity={2}/></mesh><mesh position-y={2}><octahedronGeometry args={[.22]}/><meshStandardMaterial color="#d8be84" metalness={.7}/></mesh></group>}
export function ServiceSceneManager({service,pickup,vehicle}:{service:ServiceId;pickup:Place;vehicle:VehicleId}){if(service==='self-drive')return <RentalShowroomScene vehicle={vehicle}/>;if(service==='chauffeur')return <ChauffeurScene vehicle={vehicle}/>;if(service==='airport-to-location')return <AirportScene vehicle={vehicle}/>;if(service==='location-to-airport')return <UrbanPickupScene place={pickup} vehicle={vehicle}/>;return <UrbanPickupScene place={pickup} vehicle={vehicle}/>}
